### ISSUE TITLE
Make a detailed description about the compilation process

### ISSUE THREAD

**Issue by andrasfuchs** [kxproject/kx-audio-driver#13]
I've downloaded the source from GitHub and installed Visual Studio 2015 and the WDK 10 (https://msdn.microsoft.com/en-us/windows/hardware/hh852365.aspx), but I was not able to compile the code. I wanted to edit the DDKROOT value in the set_env.bat, but it looks like the setenv.bat it refers to was removed from the DDK/WDK.

Please make a tutorial on how to make the compilation work on Windows 10.

**Comment by seven-phases-max** [comment]
I don't think it's possible to write such tutorial w/o actually ever having/using WDK10. Currently the driver is build using WDK 7.1 - so if you're going to use WDK10, you're on your own to find needed changes.

**Comment by andrasfuchs** [comment]
Ok. I downloaded the WDK 7.1 too and replaced its setenv.bat.

Now I have a few errors when I run the genall.bat file.

I got some errors because the pkware's command line tool isn't called pkzip25.exe anymore rather pkzipc.exe (version 14). I fixed that by renaming the exe, but it should be fixed in the build/nsis files.

The other problem I get is this:
NMAKE : fatal error U1077: 'c:\Work\Tools\WinDDK\7600.16385.1\bin\amd64\SignTool.EXE' : return code '0x1'

The SignTool.exe is there and can be executed from the command line. It run as administrator. Interestingly the x86 build wants to run the SignTool.exe from the amd64 folder. Both x86 and x64 builds have this error.

Do you have an idea what should I do?

(I'm running Windows 10 x64, WDK 7.1)

**Comment by linnaea** [comment]
SignTool is used to sign the binaries generated by the build process, and you need a code signing certificate for that to work. Without a valid signature Windows will refuse to load the driver. You can create a self-signed certificate but you need to put the OS in test mode, otherwise it still won't load the driver.

The change needed to get the ASIO/mixer working shouldn't touch the kernel driver part, so you should be able to just copy the user-mode binaries (kxapi.dll specifically) and use it with other parts from the official driver pack.
